### ISSUE TITLE
Webp support

### ISSUE THREAD

**Issue by xXBuilderBXx** [dicebear/api#12]
Would it be possible to add webp image format support for this?
This would mean lower download sizes for people using the API compared to png and jpg.

**Comment by FlorianKoerner** [comment]
Hi @xXBuilderBXx 

JPEG and PNG are only provided as a fallback for older environments. For newer environments, SVG should be used. For this reason there is no support for webp, because webp has no advantage over SVG. Feel free to correct me if I missed something.

**Comment by xXBuilderBXx** [comment]
SVG is nice for your own website stuff but still a lot of online services don't really support SVG uploading and/or viewing things like chat platforms such as Discord/Mastodon/Revolt/Signal and social media websites like Twitter/Facebook/etc.

Having support for webp would allow support for both those cases while also keeping the download size smaller, this would also mean lower hosting cost for the public API if developers choose to use webp over png/jpg.

**Comment by FlorianKoerner** [comment]
Good arguments. I will look into an implementation.

**Comment by FlorianKoerner** [comment]
Implemented.
https://github.com/dicebear/dicebear/releases/tag/v9.1.0
